// AUTO-GENERATED by scripts/sync-characters.mjs — do not edit by hand.
// Regenerate after adding/removing files in public/characters/lottie/:
//   npm run sync:characters

export const LOTTIE_CHARACTERS = [
  "amoeba",
  "bacterium",
  "bacterium-02",
  "bacterium-03",
  "butterfly",
  "colony",
  "mushroom-01",
  "run-01",
  "shield-01",
  "skull-01",
  "skull-02",
] as const;

export type LottieCharacterName = (typeof LOTTIE_CHARACTERS)[number];
